# frozen_string_literal: true

require 'dotenv/load'
require_relative 'app_config_loader'
require_relative 'my_application_vikovan'
require_relative 'engine'
require_relative 'archive_sender'

begin
  loader = AppConfigLoader.new

  system_libs = ['date', 'time']
  loader.load_libs(system_libs, 'libs')

  config = loader.config('config/default_config.yaml', 'config/yaml_config')

  MyApplicationVikovan::LoggerManager.initialize_logger(config)
  logger = MyApplicationVikovan::LoggerManager.logger

  logger&.info('Application: interactive main started')

  puts '=== Application Menu ==='
  puts '1. Parse website'
  puts '2. Save data to CSV'
  puts '3. Save data to JSON'
  puts '4. Save data to YAML'
  puts '5. Save data to SQLite'
  puts '6. Save data to MongoDB'
  puts '7. Parse website and save to CSV + JSON'
  puts '8. Send last archive to email'
  puts '0. Exit'
  print 'Enter actions (comma separated, e.g. 1,2,3): '

  input = STDIN.gets.to_s.strip
  selected = input.split(',').map(&:strip)

  flags = {
    run_website_parser: 0,
    run_save_to_csv: 0,
    run_save_to_json: 0,
    run_save_to_yaml: 0,
    run_save_to_sqlite: 0,
    run_save_to_mongodb: 0
  }

  user_email = nil

  selected.each do |choice|
    case choice
    when '1'
      flags[:run_website_parser] = 1
    when '2'
      flags[:run_save_to_csv] = 1
    when '3'
      flags[:run_save_to_json] = 1
    when '4'
      flags[:run_save_to_yaml] = 1
    when '5'
      flags[:run_save_to_sqlite] = 1
    when '6'
      flags[:run_save_to_mongodb] = 1
    when '7'
      flags[:run_website_parser] = 1
      flags[:run_save_to_csv] = 1
      flags[:run_save_to_json] = 1
    when '8'
      user_email = MyApplicationVikovan::ArchiveSender.prompt_email
    when '0'
      puts 'Exit selected. Nothing to do.'
      logger&.info('Application: user selected exit without actions')
      exit 0
    else
      puts "Unknown choice: #{choice}"
      logger&.warn("Application: unknown menu choice #{choice}") if logger
    end
  end

  configurator = MyApplicationVikovan::Configurator.new
  configurator.configure(flags)

  engine = MyApplicationVikovan::Engine.new(loader)
  archive_path = engine.run(configurator.config)

  if archive_path && File.exist?(archive_path)
    puts "Archive created at: #{archive_path}"
    logger&.info("Application: archive created at #{archive_path}")

    if user_email
      options = {
        'to' => user_email,
        'from' => ENV['GMAIL_USER'] || user_email,
        'subject' => 'Archive from interactive run',
        'body' => 'Archive generated by interactive run'
      }

      puts "Sending archive to #{user_email}..."
      MyApplicationVikovan::ArchiveSender.new.perform(archive_path, options)
      puts "Email sent to #{user_email}."
      logger&.info("Application: archive sent to #{user_email}")
    end
  else
    puts 'Archive was not created (maybe no output files).'
    logger&.warn('Application: archive was not created') if logger
  end

  logger&.info('Application: finished successfully')
rescue StandardError => e
  message = "Application error: #{e.class} - #{e.message}"
  if defined?(MyApplicationVikovan::LoggerManager) && MyApplicationVikovan::LoggerManager.logger
    MyApplicationVikovan::LoggerManager.log_error(message)
    MyApplicationVikovan::LoggerManager.log_error(e.backtrace.join("\n")) if e.backtrace
  else
    warn message
    warn e.backtrace.join("\n") if e.backtrace
  end
end
